name: dex
on: [push, pull_request]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # push to dockerhub when it is on release branch.
      - uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          tags: |
            aegistudio/dex:latest
            aegistudio/dex:${{github.ref_name}}

      # push to artifacts when it is not on release branch.
      - uses: docker/build-push-action@v3
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          push: false
          tags: aegistudio/dex:latest
          outputs: type=docker,dest=/tmp/dex.tar
      - uses: actions/upload-artifact@v3
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: dex.tar
          path: /tmp/dex.tar
